kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "10.10.0.0/16"
  serviceSubnet: "10.11.0.0/16"
nodes:
- role: control-plane
- role: worker
- role: worker
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EndpointSlice=true,ServiceTopology=true,EndpointSliceProxying=true"
  controllerManager:
    extraArgs:
      "feature-gates": "EndpointSlice=true,ServiceTopology=true,EndpointSliceProxying=true"
- |
  kind: KubeProxyConfiguration
  featureGates:
    EndpointSlice: true
    EndpointSliceProxying: true
    ServiceTopology: true
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
   endpoint = ["http://${reg_name}:${reg_port}"]
