kind: Cluster
apiVersion: "kind.x-k8s.io/v1alpha4"
networking:
  podSubnet: "10.12.0.0/16"
  serviceSubnet: "10.13.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:mc
- role: worker
  image: kindest/node:mc
- role: worker
  image: kindest/node:mc
kubeadmConfigPatches:
- |
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "feature-gates": "EndpointSlice=true,ServiceTopology=true,MultiClusterServices=true,EndpointSliceProxying=true"
  controllerManager:
    extraArgs:
      "feature-gates": "EndpointSlice=true,ServiceTopology=true,MultiClusterServices=true,EndpointSliceProxying=true"
- |
  kind: KubeProxyConfiguration
  featureGates:
    EndpointSlice: true
    ServiceTopology: true
    MultiClusterServices: true
    EndpointSliceProxying: true
